# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/Camera_Demo2/Camera_Demo/Camera_Demo.srcs/sources_1/ip/csi_to_axis_0/csi_to_axis_0.xci
# IP: The module: 'csi_to_axis_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Camera_Demo2/Camera_Demo/Camera_Demo.srcs/sources_1/ip/csi_to_axis_0/hdl/csi_to_axis.xdc
# XDC: The top module name and the constraint reference have the same name: 'csi_to_axis_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FPGA/Camera_Demo2/Camera_Demo/Camera_Demo.srcs/sources_1/ip/csi_to_axis_0/csi_to_axis_0.xci
# IP: The module: 'csi_to_axis_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Camera_Demo2/Camera_Demo/Camera_Demo.srcs/sources_1/ip/csi_to_axis_0/hdl/csi_to_axis.xdc
# XDC: The top module name and the constraint reference have the same name: 'csi_to_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
